# Reading the Train File for en-us text

In [53]:
# Returns {Line : Article}

def readnormalcorpus():
    linetest=0
    corpus={}
    fi=open("normal","r")
    for line in fi:
        line=line.lower()
        linetest+=1
        if linetest > 1000:
            break
        corpus[[((line[:-1].split("\t")))[2]][0]]=[((line[:-1].split("\t")))[0]][0];
    return corpus

readnormalcorpus()

{"`` old school '' boards -lrb- those made in the 1970s \xc3\xa2 `` 80s or modern boards that mimic their shape -rrb- are generally wider and often have only one kicktail .": 'skateboard',
 "annual events in cardiff that have become regular appearances in cardiff 's calendar include sparks in the park , the great british cheese festival , cardiff mardi gras , cardiff winter wonderland and cardiff festival .": 'cardiff',
 'cardiff has many cultural sites varying from the historical cardiff castle and out of town castell coch to the more modern wales millennium centre and cardiff bay . cardiff was a finalist in the european capital of culture 2008 .': 'cardiff',
 'cherokee is a city in alfalfa county , oklahoma , united states .': 'cherokee, oklahoma',
 'cond\xc3\x83 - sur-ifs is a commune in the calvados department in the basse-normandie region in northwestern france .': 'cond\xc3\x83\xc2\xa9-sur-ifs',
 'edmilson alves -lrb- born february 17 , 1976 -rrb- , is a brazilian midfielder who 

# Reading Train File for Simple Text

In [54]:
# Returns {Line : Article}

def readsimplecorpus():
    linetest=0
    corpus={}
    fi=open("simple","r")
    for line in fi:
        line=line.lower()
        linetest+=1
        if linetest > 1000:
            break
        corpus[[((line[:-1].split("\t")))[2]][0]]=[((line[:-1].split("\t")))[0]][0];
    return corpus

readsimplecorpus()

{"`` old school '' boards -lrb- those made in the 1970s \xc3\xa2 `` 80s -rrb- are mostly wider and often have only one kicktail .": 'skateboard',
 'cardiff has a big port that used to be known as tiger bay , now just called cardiff bay , where the welsh government works and now there are lots of shops , pubs and restaurants . cardiff has an international airport , and is twinned with nantes in france and stuttgart in germany .': 'cardiff',
 'cardiff has one of the largest stadiums in the united kingdom , the millennium stadium , where important world sports matches and concerts happen . other big stadiums in the city are the cardiff city stadium , where the main football and rugby teams play , and the swalec stadium where cricket is played .': 'cardiff',
 'cardiff is the capital and biggest city of wales , in the united kingdom .': 'cardiff',
 'cherokee is a city of oklahoma in the united states .': 'cherokee, oklahoma',
 'different kinds of the 1970s often have little or no concavity 

# Building a Trigram Model

In [55]:
from itertools import tee, izip

def window(iterable, size):
    iters = tee(iterable, size)
    for i in xrange(1, size):
        for each in iters[i:]:
            next(each, None)
    return izip(*iters)

def tri_model():
    
    normal_corpus = readnormalcorpus()
    simple_corpus = readsimplecorpus()
    
    tgm_normal={}
    tgm_simple={}
        
    for i in normal_corpus.keys():
        for each in window(i.split(), 3):
            temp=list(each)
            if tgm_normal.has_key(tuple(temp)):
                tgm_normal[tuple(list(each))]+=1
            else:
                tgm_normal[tuple(list(each))]=1
    
                
    for i in simple_corpus.keys():
        for each in window(i.split(), 3):
            temp=list(each)
            if tgm_simple.has_key(tuple(temp)):
                tgm_simple[tuple(list(each))]+=1
            else:
                tgm_simple[tuple(list(each))]=1

    return tgm_normal,tgm_simple

tri_model()

({("'", ',', 'the'): 1,
  ("'", '\xc3\x98', 'cents'): 1,
  ("''", 'boards', '-lrb-'): 1,
  ("''", 'taken', 'from'): 1,
  ("'s", 'calendar', 'include'): 1,
  ("'s", 'feet', 'grip'): 1,
  ("'s", 'is', 'far'): 1,
  ("'s", 'second', 'name'): 1,
  (',', ',', ','): 3,
  (',', ',', 'literally'): 1,
  (',', '1976', '-rrb-'): 1,
  (',', 'a', 'common'): 1,
  (',', 'allowing', 'the'): 1,
  (',', 'aluminum', ','): 1,
  (',', 'an', 'academy'): 1,
  (',', 'and', 'griptape'): 1,
  (',', 'and', 'is'): 1,
  (',', 'and', 'plastic'): 1,
  (',', 'and', 'was'): 1,
  (',', 'bamboo', ','): 1,
  (',', 'bearings', ','): 1,
  (',', 'blank', ','): 1,
  (',', 'but', 'most'): 1,
  (',', 'carbon', 'fiber'): 1,
  (',', 'cardiff', 'city'): 1,
  (',', 'cardiff', 'international'): 1,
  (',', 'cardiff', 'mardi'): 1,
  (',', 'cardiff', 'winter'): 1,
  (',', 'formerly', 'the'): 1,
  (',', 'forming', 'the'): 1,
  (',', 'gives', 'a'): 1,
  (',', 'hardware', ','): 1,
  (',', 'has', 'a'): 1,
  (',', 'india', '.'): 2,
  (',', 

# First, Defining a Naive Bias Model for Classification

This function takes a trigram input and does a simple vs normal classification. As the trigram which is normal is also present in simple we classify it in simple.

In [64]:
def naive_classifier(sentence):
    tgm_normal,tgm_simple=tri_model()
    sentence=sentence.lower()
    score_simple=0
    score_normal=0
    total_simple=sum(tgm_simple.values())
    total_normal=sum(tgm_normal.values())
    print sentence
    for each in window(sentence.split(), 3):
        temp=list(each)
        if(tgm_simple.has_key(tuple(temp))):
            score_simple+=tgm_simple[tuple(temp)]*1.0/total_simple
        else :
            score_simple+=0.000003
        if(tgm_normal.has_key(tuple(temp))):
            score_normal+=tgm_normal[tuple(temp)]*1.0/total_normal
        else:
            score_normal+=0.000003
    
    print score_simple
    print score_normal
    if(score_normal>score_simple):
        print "NORMAL"
    else:
        print "SIMPLE"

sentence="Different kinds of the 1970s often have little or no concavity , whereas 1980s models have deeper concavities and steeper kicktails ."        
naive_classifier(sentence)
       
    

different kinds of the 1970s often have little or no concavity , whereas 1980s models have deeper concavities and steeper kicktails .
0.0380228136882
0.021718907117
SIMPLE


# Defining a logestic Regression Model

In [83]:
class LogisticRegression:
    def __init__(self, lr=0.01, num_iter=100000, fit_intercept=True, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        self.verbose = verbose
    
    def __add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    def __loss(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    
    def fit(self, X, y):
        if self.fit_intercept:
            X = self.__add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            gradient = np.dot(X.T, (h - y)) / y.size
            self.theta -= self.lr * gradient
            
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            loss = self.__loss(h, y)
                
            if(self.verbose ==True and i % 10000 == 0):
                print(f'loss: {loss} \t')
    
    def predict_prob(self, X):
        if self.fit_intercept:
            X = self.__add_intercept(X)
    
        return self.__sigmoid(np.dot(X, self.theta))
    
    def predict(self, X):
        return self.predict_prob(X).round()

SyntaxError: invalid syntax (<ipython-input-83-b7f9674b559b>, line 35)

In [86]:
# load the iris dataset 
from sklearn.datasets import load_iris 
iris = load_iris() 

# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target 

# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1) 

# training the model on training set 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train, y_train) 

print X_train

# making predictions on the testing set 
y_pred = gnb.predict(X_test) 

# comparing actual response values (y_test) with predicted response values (y_pred) 
from sklearn import metrics 
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

[[4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [4.4 3.  1.3 0.2]
 [6.  2.7 5.1 1.6]
 [6.4 2.7 5.3 1.9]
 [5.9 3.  5.1 1.8]
 [5.2 3.5 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [5.8 2.7 4.1 1. ]
 [4.9 3.1 1.5 0.1]
 [7.4 2.8 6.1 1.9]
 [6.2 2.9 4.3 1.3]
 [7.6 3.  6.6 2.1]
 [6.7 3.  5.2 2.3]
 [6.3 2.3 4.4 1.3]
 [6.2 3.4 5.4 2.3]
 [7.2 3.6 6.1 2.5]
 [5.6 2.9 3.6 1.3]
 [5.7 4.4 1.5 0.4]
 [5.8 2.7 3.9 1.2]
 [4.5 2.3 1.3 0.3]
 [5.5 2.4 3.8 1.1]
 [6.9 3.1 4.9 1.5]
 [5.  3.4 1.6 0.4]
 [6.8 2.8 4.8 1.4]
 [5.  3.5 1.6 0.6]
 [4.8 3.4 1.9 0.2]
 [6.3 3.4 5.6 2.4]
 [5.6 2.8 4.9 2. ]
 [6.8 3.2 5.9 2.3]
 [5.  3.3 1.